language: node_js
node_js:
  - '0.10'
  - '0.8'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-aurelia-dropwizard' ]; then cd .. && eval "mv $currentfolder generator-aurelia-dropwizard" && cd generator-aurelia-dropwizard; fi

